"""
Document Agent — generates letters and PDFs from Jinja2 templates.
"""
import uuid
from pathlib import Path
from datetime import date, datetime

from jinja2 import Environment, FileSystemLoader
from fpdf import FPDF

from core.models import DeceasedProfile, GeneratedDocument
from core.storage import get_docs_dir, save_document, load_profile

_TEMPLATES_DIR = Path(__file__).parent.parent / "templates"
_jinja_env = Environment(loader=FileSystemLoader(str(_TEMPLATES_DIR)))


def _render_template(template_name: str, context: dict) -> str:
    """Render a Jinja2 template to a string."""
    tmpl = _jinja_env.get_template(f"{template_name}.j2")
    return tmpl.render(**context)


def _text_to_pdf(text: str, output_path: Path, title: str):
    """Convert plain text to a clean PDF using fpdf2."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 10, "EstatePath — Official Correspondence", ln=True, align="C")
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(127, 140, 141)
    pdf.cell(0, 6, "This document was generated to assist with estate administration. Review before sending.", ln=True, align="C")
    pdf.ln(4)

    # Divider
    pdf.set_draw_color(189, 195, 199)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # Body
    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(44, 62, 80)
    for line in text.split("\n"):
        if line.strip() == "":
            pdf.ln(4)
        else:
            pdf.multi_cell(0, 6, line)

    # Footer
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(127, 140, 141)
    pdf.cell(0, 10, f"Generated by EstatePath on {date.today().strftime('%B %d, %Y')} | Review before sending | Not legal advice", align="C")

    pdf.output(str(output_path))


def generate_letter(
    template_name: str,
    task_id: str,
    institution: str,
    account_number: str = "",
    institution_address: str = "",
    extra_context: dict = None,
) -> GeneratedDocument:
    """Generate a letter PDF and return a GeneratedDocument."""
    profile: DeceasedProfile = load_profile()
    if not profile:
        raise ValueError("No estate profile found. Please complete intake first.")

    context = {
        "executor_name": profile.executor_name,
        "executor_address": profile.executor_address,
        "executor_city_state_zip": profile.executor_city_state_zip,
        "executor_phone": profile.executor_phone,
        "executor_email": profile.executor_email,
        "deceased_name": profile.full_name,
        "deceased_dob": profile.date_of_birth,
        "date_of_death": profile.date_of_death,
        "state": profile.state_of_residence,
        "today_date": date.today().strftime("%B %d, %Y"),
        "institution_name": institution,
        "institution_address": institution_address or "[Institution Address]",
        "account_number": account_number,
    }
    if extra_context:
        context.update(extra_context)

    text = _render_template(template_name, context)

    # Save PDF
    docs_dir = get_docs_dir()
    slug = task_id.replace("-", "_")
    inst_slug = institution.lower().replace(" ", "_").replace("/", "_")[:20]
    filename = f"{slug}_{inst_slug}_{date.today().isoformat()}.pdf"
    file_path = docs_dir / filename

    title = f"{template_name.replace('_', ' ').title()} — {institution}"
    _text_to_pdf(text, file_path, title)

    doc = GeneratedDocument(
        doc_id=str(uuid.uuid4())[:8],
        task_id=task_id,
        title=title,
        institution=institution,
        created_at=datetime.now().isoformat(),
        file_path=str(file_path),
        template_used=template_name,
    )
    save_document(doc)
    return doc
